 _format_version: "3.0"
 _transform: true

 services:
 - host: httpbin.org
   name: example_service
   port: 443
   protocol: https
   routes:
   - name: example_route
     paths:
     - /mock
     strip_path: true